version: 1.1.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  marketplacepublishtoken:
    secure: xCM8+dV2BwpXo0fYuON1ag2n5dLZHLrC7ak5wPWTor4dG7DQi89/ya0woibcu1FV3bkJkBpvbgfbfqG3ezy1pA==
  matrix:
  - {}
before_build:
- ps: >-
    nuget restore

    .\tools\update-vsixversion.ps1 $($env:appveyor_build_version)
build:
  project: Telia.GraphQL.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: JJqRZ9VeHydrhH6UroXmGo0RaZsTvDs6txFts2F+bnEVVVbir6iPVHyIsHaos1BL
  on:
    branch: master
after_deploy:
- ps: .\tools\publish-vsix.ps1